# .pre-commit-config.yaml
minimum_pre_commit_version: "3.5.0"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-format
        exclude: ^src/ci/transparency/types/.*\.py$
      - id: ruff  
        exclude: ^src/ci/transparency/types/.*\.py$

  - repo: local
    hooks:
      # Quick version/spec invariants (no generation). Runs when pyproject or code changes.
      - id: check-version-compatibility
        name: Check version compatibility (current env)
        entry: python .github/scripts/check_version_compatibility.py
        language: system
        files: ^(pyproject\.toml|src/.*\.py|\.github/scripts/.*\.py)$
        pass_filenames: false

      # Import smoke + empty points invariant — no generation.
      - id: verify-types
        name: Verify types import + empty points
        entry: python .github/scripts/verify_types.py
        language: system
        pass_filenames: false

      # NOTE: Generation is intentionally manual to keep CI pure-validate.
      # Run locally when spec changes:
      #   python scripts/generate_types.py && git add src/ci/transparency/types/
