# .github/workflows/ci.yml
name: Civic Transparency Types CI (Build Types, Lint, Test, Coverage)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout (full history) # so setuptools_scm can see tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install codegen deps only (no editable install)
        run: |
          python -m pip install --upgrade pip
          pip install ".[codegen]"

      # Keep generated models in sync with the published spec
      - name: Regenerate types
        run: python scripts/generate_types.py

      - name: Check for uncommitted changes (generated code up-to-date)
        run: git diff --exit-code

      - name: Install dev deps (extras, non-editable)
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Ruff lint (check only, no format or auto-fix in CI)
        run: ruff check .

      - name: Run tests (with any validation and coverage)
        run: pytest -q

      - name: Generate coverage summary
        if: always()
        run: python .github/scripts/coverage_summary.py

      - name: Build HTML coverage and upload
        if: always()
        run: coverage html

      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml

      - name: Build docs (sanity check)
        run: mkdocs build

      - name: Build package (sanity check)
        run: python -m build
