# .github/workflows/deploy-docs.yml
name: Deploy CT Types Docs (always latest main)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # gh-pages in docs job
    
    steps:
      - name: Checkout (full history) # so setuptools_scm can see tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install docs deps (from extras, non-editable)
        run: |
          python -m pip install --upgrade pip
          pip install ".[docs]"

      - name: Ensure gh-pages branch exists locally
        run: |
          git fetch origin gh-pages:gh-pages || true

      - name: Configure git for mike
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build docs (fail fast)
        run: mkdocs build

      - name: Deploy docs with Mike & set latest
        run: |
          mike deploy --push --update-aliases latest main
          mike set-default --push latest
